### ISSUE TITLE
yellow triangle icon

### ISSUE THREAD

**Issue by djthoz91** [courtarro/adsb-monitor#1]
hi ,
in google map
is it possible to replace the yellow triangle icons by icons of aircraft as in dump1090 ?

thank you

**Comment by courtarro** [comment]
The Google Maps API should support this.

You can see where the symbol is set in [js/gmap.js](https://github.com/courtarro/adsb-monitor/blob/master/js/gmap.js#L27)

[This Google page](https://developers.google.com/maps/documentation/javascript/symbols) describes symbol selection.
